//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class emptable
    {
        public int EMPid { get; set; }
        public string FullName { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public Nullable<int> DivisionCode { get; set; }
        public string Division { get; set; }
        public string Supervisor { get; set; }
        public string Email { get; set; }
        public string Department { get; set; }
    }
}
